# Generated by Django 5.2.8 on 2025-11-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
