# Generated by Django 5.2.8 on 2025-11-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_deleted_alter_order_item_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
