# Generated by Django 5.2.8 on 2025-11-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_number_alter_order_price_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
