# Generated by Django 5.2.8 on 2025-11-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_price_sum'),
        ('products', '0006_remove_cart_user_remove_cart_item_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
