# Generated by Django 5.2.8 on 2025-12-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_order_date_order_created_at'),
        ('products', '0014_rename_parametr_product_parameters_parameter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_item',
            new_name='OrderItem',
        ),
    ]
