# Generated by Django 5.2.8 on 2025-12-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Создан'), ('Work', 'В работе'), ('Sent', 'Отправлен'), ('Done', 'Готов к выдаче'), ('Completed', 'Завершен'), ('Canceled', 'Отменен')], default='Created'),
        ),
    ]
