# Generated by Django 5.2.8 on 2026-04-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Создан'), ('Work', 'В работе'), ('Sent', 'Отправлен'), ('Done', 'Готов к выдаче'), ('Completed', 'Завершен'), ('Canceled', 'Отменен')], default='Created', max_length=20),
        ),
    ]
