# Generated by Django 5.2.8 on 2025-11-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_category_manager_user_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
