# Generated by Django 5.2.8 on 2025-11-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Создан'), ('Sent', 'В пути'), ('Completed', 'Завершен')], default='Created'),
        ),
    ]
