# Generated by Django 5.2.8 on 2025-12-02 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_parameters',
            name='name',
        ),
        migrations.AlterField(
            model_name='product_parameters',
            name='value',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='product_parameters',
            name='parametr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.parameter'),
        ),
    ]
