# Generated by Django 5.2.8 on 2025-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_parameters_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
