# Generated by Django 5.2.8 on 2025-12-02 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_parameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_parameters',
            name='parametr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.parameter'),
        ),
    ]
