# Generated by Django 5.2.8 on 2025-12-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_parameter_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_parameters',
            old_name='parametr',
            new_name='parameter',
        ),
    ]
