# Generated by Django 5.2.8 on 2025-12-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_pass',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
