# Generated by Django 5.2.8 on 2026-03-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_rename_product_parameters_productparameters_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductParameters',
            new_name='ProductParameter',
        ),
    ]
