# Generated by Django 5.2.8 on 2026-03-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_rename_productparameters_productparameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_pass',
            new_name='image_path',
        ),
    ]
