# Generated by Django 5.2.8 on 2026-03-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.CharField(default='', max_length=500),
        ),
    ]
