# Generated by Django 5.2.8 on 2026-03-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_productparameter_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
