# Generated by Django 5.2.8 on 2026-03-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_avg',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True),
        ),
    ]
