# Generated by Django 5.2.8 on 2026-04-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='brands/'),
        ),
    ]
