# Generated by Django 5.2.8 on 2026-04-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_brand_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_path',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='reviews/'),
        ),
    ]
