# Generated by Django 5.2.8 on 2026-03-27 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_item_product'),
        ('products', '0025_rename_image_pass_product_image_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_item',
            new_name='CartItem',
        ),
    ]
