# Generated by Django 5.2.8 on 2026-03-27 09:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_cart_item_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user',)},
        ),
    ]
